# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.micheal.wang:3306/micheal-blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mingkai13
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml